name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18.16
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Creating .env file
        uses: weyheyhey/create-dotenv-action@v1
        env:
          ^DB_HOST: ${{ secrets.DB_HOST }}
          ^DB_PORT: ${{ secrets.DB_PORT }}
          ^DB_USERNAME: ${{ secrets.DB_USERNAME }}
          ^DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ^DB_NAME: ${{ secrets.DB_NAME }}
          ^NODE_ENV: ${{ secrets.NODE_ENV }}
        with:
          wildecard: "^"
          filename: ".env"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      # - name: Run e2e tests
      #   run: npm run test:e2e

      - name: Typescript build
        run: npm run build
